version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: code-editor-backend
    ports:
      - "8003:8003"
    env_file:
      - ./backend/.env
    environment:
      - HOST_PROJECT_PATH=C:/Users/ramku/OneDrive/Desktop/new_folder/golang/project-3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./code-exec:/code-exec
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine
    container_name: code-editor-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  # # Frontend service (if you have one—e.g. React/Vite)
  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: compiler-frontend
  #   ports:
  #     - "3000:3000"
  #   # If your frontend talks to the backend at /execute:
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:8000
